// js/data.js
export const recipes = [
  {
    id: 1,
    name: "Paneer Butter Masala",
    time: "30 mins",
    type: "Vegetarian",
    image: "https://source.unsplash.com/800x500/?paneer,curry",
    ingredients: [
      "Paneer",
      "Butter",
      "Tomato puree",
      "Cream",
      "Garam masala",
      "Spices",
    ],
    steps: [
      "Heat butter in a pan",
      "Add tomato puree and spices",
      "Add paneer cubes",
      "Add cream and simmer",
    ],
  },
  {
    id: 2,
    name: "Grilled Chicken",
    time: "35 mins",
    type: "Non-Vegetarian",
    image: "https://source.unsplash.com/800x500/?grilled,chicken",
    ingredients: [
      "Chicken",
      "Olive oil",
      "Garlic",
      "Lemon juice",
      "Spices",
    ],
    steps: [
      "Marinate the chicken",
      "Preheat the grill",
      "Grill chicken until cooked",
    ],
  },
  {
    id: 3,
    name: "Veg Pasta",
    time: "25 mins",
    type: "Vegetarian",
    image: "https://source.unsplash.com/800x500/?vegetable,pasta",
    ingredients: [
      "Pasta",
      "Bell peppers",
      "Onions",
      "Garlic",
      "Olive oil",
      "Italian herbs",
    ],
    steps: [
      "Boil pasta until al dente",
      "Sauté vegetables in olive oil",
      "Mix pasta with vegetables",
      "Add herbs and serve",
    ],
  },
  {
    id: 4,
    name: "Avocado Salad",
    time: "15 mins",
    type: "Vegan",
    image: "https://source.unsplash.com/800x500/?avocado,salad",
    ingredients: [
      "Avocado",
      "Tomatoes",
      "Cucumber",
      "Lemon juice",
      "Olive oil",
    ],
    steps: [
      "Chop all vegetables",
      "Mix in a bowl",
      "Add lemon juice and olive oil",
      "Toss and serve fresh",
    ],
  },
  {
    id: 5,
    name: "Egg Curry",
    time: "30 mins",
    type: "Non-Vegetarian",
    image: "https://source.unsplash.com/800x500/?egg,curry",
    ingredients: [
      "Boiled eggs",
      "Onions",
      "Tomatoes",
      "Ginger garlic paste",
      "Spices",
    ],
    steps: [
      "Sauté onions until golden",
      "Add tomatoes and spices",
      "Add boiled eggs",
      "Simmer for 10 minutes",
    ],
  },
  {
    id: 6,
    name: "Chickpea Stir Fry",
    time: "20 mins",
    type: "Vegan",
    image: "https://source.unsplash.com/800x500/?chickpeas,vegetables",
    ingredients: [
      "Boiled chickpeas",
      "Bell peppers",
      "Onions",
      "Garlic",
      "Spices",
    ],
    steps: [
      "Heat oil in a pan",
      "Add garlic and onions",
      "Add chickpeas and vegetables",
      "Cook until lightly crisp",
    ],
  },
];
